// Generated 14/07/2014 11:15:24 AM by Hibernate Tools 3.4.0.CR1
package co.com.inversionesxyz.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nombreUsuario;
	private String password;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Analista> analistas = new HashSet<Analista>(0);

	public Cuenta() {
	}

	public Cuenta(String nombreUsuario, String password) {
		this.nombreUsuario = nombreUsuario;
		this.password = password;
	}

	public Cuenta(String nombreUsuario, String password, Set<Cliente> clientes,
			Set<Analista> analistas) {
		this.nombreUsuario = nombreUsuario;
		this.password = password;
		this.clientes = clientes;
		this.analistas = analistas;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	public Set<Analista> getAnalistas() {
		return this.analistas;
	}

	public void setAnalistas(Set<Analista> analistas) {
		this.analistas = analistas;
	}

}
