// Generated 14/07/2014 11:15:24 AM by Hibernate Tools 3.4.0.CR1
package co.com.inversionesxyz.dto;

import java.util.Date;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private Solicitud solicitud;
	private String respuestaPreguntaA;
	private String respuestaPreguntaB;
	private Date fechaEnvio;

	public Encuesta() {
	}

	public Encuesta(String id, Solicitud solicitud, String respuestaPreguntaA,
			String respuestaPreguntaB, Date fechaEnvio) {
		this.id = id;
		this.solicitud = solicitud;
		this.respuestaPreguntaA = respuestaPreguntaA;
		this.respuestaPreguntaB = respuestaPreguntaB;
		this.fechaEnvio = fechaEnvio;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public String getRespuestaPreguntaA() {
		return this.respuestaPreguntaA;
	}

	public void setRespuestaPreguntaA(String respuestaPreguntaA) {
		this.respuestaPreguntaA = respuestaPreguntaA;
	}

	public String getRespuestaPreguntaB() {
		return this.respuestaPreguntaB;
	}

	public void setRespuestaPreguntaB(String respuestaPreguntaB) {
		this.respuestaPreguntaB = respuestaPreguntaB;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

}
