// Generated 14/07/2014 11:15:24 AM by Hibernate Tools 3.4.0.CR1
package co.com.inversionesxyz.dto;

/**
 * ClienteId generated by hbm2java
 */
public class ClienteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String tipoDocumento;
	private String numeroDocumento;

	public ClienteId() {
	}

	public ClienteId(String tipoDocumento, String numeroDocumento) {
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteId))
			return false;
		ClienteId castOther = (ClienteId) other;

		return ((this.getTipoDocumento() == castOther.getTipoDocumento()) || (this
				.getTipoDocumento() != null
				&& castOther.getTipoDocumento() != null && this
				.getTipoDocumento().equals(castOther.getTipoDocumento())))
				&& ((this.getNumeroDocumento() == castOther
						.getNumeroDocumento()) || (this.getNumeroDocumento() != null
						&& castOther.getNumeroDocumento() != null && this
						.getNumeroDocumento().equals(
								castOther.getNumeroDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTipoDocumento() == null ? 0 : this.getTipoDocumento()
						.hashCode());
		result = 37
				* result
				+ (getNumeroDocumento() == null ? 0 : this.getNumeroDocumento()
						.hashCode());
		return result;
	}

}
