package co.com.inversionesxyz.dto;

// default package
// Generated 19/07/2014 12:28:09 AM by Hibernate Tools 3.4.0.CR1

/**
 * InformacionAnalista generated by hbm2java
 */
public class InformacionAnalista implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dni;
	private Solicitud solicitud;
	private String nombre;
	private String apellidos;
	private String direccion;
	private String pais;
	private String ciudad;

	public InformacionAnalista() {
	}

	public InformacionAnalista(String dni, Solicitud solicitud, String nombre,
			String apellidos, String direccion, String pais, String ciudad) {
		this.dni = dni;
		this.solicitud = solicitud;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.pais = pais;
		this.ciudad = ciudad;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

}
