package com.xyz.dto;

// Generated 4/07/2014 07:36:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private String nombreUsuario;
	private String password;
	private Set clientes = new HashSet(0);
	private Set analistas = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(String nombreUsuario, String password) {
		this.nombreUsuario = nombreUsuario;
		this.password = password;
	}

	public Cuenta(String nombreUsuario, String password, Set clientes,
			Set analistas) {
		this.nombreUsuario = nombreUsuario;
		this.password = password;
		this.clientes = clientes;
		this.analistas = analistas;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

	public Set getAnalistas() {
		return this.analistas;
	}

	public void setAnalistas(Set analistas) {
		this.analistas = analistas;
	}

}
