package com.xyz.dto;

// Generated 4/07/2014 07:36:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private ClienteId id;
	private Cuenta cuenta;
	private String nombres;
	private String apellidos;
	private Date fechaNacimiento;
	private String sexo;
	private Set solicituds = new HashSet(0);
	private Set detalleClientes = new HashSet(0);

	public Cliente() {
	}

	public Cliente(ClienteId id, Cuenta cuenta, String nombres,
			String apellidos, Date fechaNacimiento, String sexo) {
		this.id = id;
		this.cuenta = cuenta;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.sexo = sexo;
	}

	public Cliente(ClienteId id, Cuenta cuenta, String nombres,
			String apellidos, Date fechaNacimiento, String sexo,
			Set solicituds, Set detalleClientes) {
		this.id = id;
		this.cuenta = cuenta;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.sexo = sexo;
		this.solicituds = solicituds;
		this.detalleClientes = detalleClientes;
	}

	public ClienteId getId() {
		return this.id;
	}

	public void setId(ClienteId id) {
		this.id = id;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Set getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set solicituds) {
		this.solicituds = solicituds;
	}

	public Set getDetalleClientes() {
		return this.detalleClientes;
	}

	public void setDetalleClientes(Set detalleClientes) {
		this.detalleClientes = detalleClientes;
	}

}
