package com.xyz.dto;

// Generated 4/07/2014 07:36:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String preguntaA;
	private String preguntaB;
	private Date fechaEnvio;

	public Encuesta() {
	}

	public Encuesta(String id, String preguntaA, String preguntaB,
			Date fechaEnvio) {
		this.id = id;
		this.preguntaA = preguntaA;
		this.preguntaB = preguntaB;
		this.fechaEnvio = fechaEnvio;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPreguntaA() {
		return this.preguntaA;
	}

	public void setPreguntaA(String preguntaA) {
		this.preguntaA = preguntaA;
	}

	public String getPreguntaB() {
		return this.preguntaB;
	}

	public void setPreguntaB(String preguntaB) {
		this.preguntaB = preguntaB;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

}
