package com.xyz.dto;

// Generated 4/07/2014 07:36:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private String direccion;
	private String pais;
	private String ciudad;
	private Set productos = new HashSet(0);

	public Sucursal() {
	}

	public Sucursal(String codigo, String nombre, String direccion,
			String pais, String ciudad) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.direccion = direccion;
		this.pais = pais;
		this.ciudad = ciudad;
	}

	public Sucursal(String codigo, String nombre, String direccion,
			String pais, String ciudad, Set productos) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.direccion = direccion;
		this.pais = pais;
		this.ciudad = ciudad;
		this.productos = productos;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
