package co.com.inversionesxyz.dto;

// default package
// Generated 14/07/2014 11:15:24 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Analista generated by hbm2java
 */
public class Analista implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dni;
	private Cuenta cuenta;
	private Rol rol;
	private String nombre;
	private String apellidos;
	private String direccion;
	private String pais;
	private String ciudad;
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

	public Analista() {
	}

	public Analista(String dni, Cuenta cuenta, Rol rol, String nombre,
			String apellidos, String direccion, String pais, String ciudad) {
		this.dni = dni;
		this.cuenta = cuenta;
		this.rol = rol;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.pais = pais;
		this.ciudad = ciudad;
	}

	public Analista(String dni, Cuenta cuenta, Rol rol, String nombre,
			String apellidos, String direccion, String pais, String ciudad,
			Set<Solicitud> solicituds) {
		this.dni = dni;
		this.cuenta = cuenta;
		this.rol = rol;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.pais = pais;
		this.ciudad = ciudad;
		this.solicituds = solicituds;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

}
